<template>
  <div class="portfolio">
    <p>Here I've listed some of the projects I've built that best demonstrate my abilites and interests. With the
      exception of Verus, all of these
      projects are open source so feel free to copy anything you like. None of these
      are tutorials or class assignments unless otherwise stated.</p>
    <div id="project-github">
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.verusProject" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.fintech80" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.codeNamesProject" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.sentenceClassifications" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.operatingSystemStudySite" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.classificationProject" />
      <ProjectGithubComponentVue class="project-github-component-vue" :data="state.arduinoTwosComplementProject" />
    </div>
  </div>
</template>
<script setup>
import { reactive } from 'vue';
import ProjectGithubComponentVue from '@/components/ProjectGithubComponent.vue';

const fintech80 = {
  title: 'Policy Royale - Fintech80 Hackathon Winner',
  description: [
    "Policy Royale is a B2B SaaS platform developed for underwriting insurance policies for autonomous vehicles. It combines cutting-edge RAG (Retrieval-Augmented Generation) technology with advanced data science to generate tailored policies dynamically.",
    "I built the frontend using Vue.js, creating a seamless and responsive user interface. The backend, developed in Python, integrates an OpenAI API with real-time data pipelines to analyze autonomous driving metrics.",
    "The platform features dynamic policy generation based on real-time data, enabling customized pricing and policy structures based on driving behaviors. Policy Royale secured first place at the FinTech80 Hackathon in Chengdu, China, competing against top-tier teams."
  ],
  photo: require('@/assets/fintech80.jpg'), // Replace with the actual path to your logo file
  githubUrl: "https://github.com/aclarke500/fintech-80",
  websiteUrl: "https://jazzy-madeleine-4ecbee.netlify.app/",
};


const codeNamesProject = {
  title: 'QMIND Code Names AI',
  description:[
    "This is a project I worked on as part QMIND's Division of AI Research (DAIR) team. My team and I used Pytorch to train a model that considers both positive and negative aspects in order to fine tune a specific answer. The result is a vector search algorithm that can very quickly find the optimal hint.",
    'My role with for this project was to collaborate on the model, as well as building the front end to show off the app at CUCAI.',
    'The result is an extremely effective agent for codenames, guessing on average 5.6 words per turn and absolutely dominating human players.',
  ],
  photo: require('@/assets/DALLeCodeNames.jpg'),
  githubUrl: 'https://github.com/aclarke500/qmind-codenames-front-end',
  websiteUrl: null,
}

const sentenceClassifications = {
  title: 'Research Project: Neural Networks vs. Explainable Methods for Genre Classification',
  description: [
    "This research project investigates the performance of neural networks compared to simpler, more explainable methods such as Euclidean distance for genre classification. Using data from sources like the 'Am I the Asshole' subreddit and the 'Attention is All You Need' paper, the project explores the effectiveness of each approach for classifying sentences by genre.",
    "What I found was that Euclidean distance, a much simpler centroid-based method, outperformed neural networks on the datasets tested. Centroids were generated by mean-pooling sentence embeddings from the 'paraphrase-MiniLM-L6-v2' model in SentenceTransformers, and test sentences were classified based on their distance from these centroids.",
    "The project is a full-stack application, with the backend built using Flask and PyTorch to handle embedding generation and analysis, and the frontend developed in Vue.js for both visualizing classification results and creating an interactive demo. This research highlights the potential of explainable methods in scenarios where interpretability and computational efficiency are critical."
  ],
  photo: require('@/assets/sentence_classification.jpg'), // Replace with the actual path to your image file
  githubUrl: "https://github.com/aclarke500/sentence-classifications",
  websiteUrl: null,
};

const verusProject = {
  title: 'Verus AMB',
  description: [
    "Veurs AMB is a company I co-founded in first year. It's a VueFire application that serves to automate and optimize billing practices. Physicians simply take a photo of their daily schedule, and Verus selects the most appropriate billing option based on the 1000 page OHIP billing manual. The app then generates a billing report, and sends it to the physician's secretary for a hands off billing solution. The app is currently in beta testing, and is scheduled to pilot at the Kingston General Hospital in the coming months."
  ],
  photo: require('@/assets/DALLe.png'),

  websiteUrl: "https://www.verusamb.com/",
  githubUrl: null,
}


const operatingSystemStudySite = {
  title: 'Operating Systems Study Site',
  description: [
    "This is a project in AI generated content. I did not like going to my OS class, nor did I have the time to read the textbook. I used chatGPT to skim my textbook, and I passed in my assigned readings and asked it to make notes in html. From there, I put the notes it generated onto a website, and modified it slightly. Most of the code, styling, and all of the images and art associated with it are AI generated. As much as it was about studying for my OS class, it was also about leveraging AI to automate work as a developer."
  ],
  githubUrl: "https://github.com/aclarke500/CISC-324-Notes",
  websiteUrl: "https://aclarke500.github.io/CISC-324-Notes/",
  photo: require('@/assets/os_project.png'),
}



const classificationProject = {
  title: 'Custom Classification Algorithm',
  description: [
    "This is a classification algorithm I designed and implemented from scratch. The idea came to me when I was playing around with properties of vectors and matrices, and realized I could build a supervised classification algorithm using p-values and dot products."
  ],
  githubUrl: 'https://github.com/aclarke500/custom-classification-algorithm',
  photo: require('@/assets/ML_project.png'),
  websiteURL: null,
}

const arduinoTwosComplementProject = {
  title: "Bitz Clash",
  description: [
    "This is a game I built that tests your binary skills. You are presented with a math equation, adding or subtracting numbers between [-50 and +50]. You must then input your answer in binary using the buttons on the bread board. You can also toggle between signed and unsigned ints in order to use 2s complement."],
  photo: require('@/assets/arduino_photo.png'),
  websiteUrl: "https://photos.app.goo.gl/f9JzjAd5LKtxUsRSA",
  githubUrl: "https://github.com/aclarke500/binary-addition-game",
}


const state = reactive({
  classificationProject: classificationProject,
  arduinoTwosComplementProject: arduinoTwosComplementProject,
  operatingSystemStudySite: operatingSystemStudySite,
  verusProject: verusProject,
  codeNamesProject: codeNamesProject,
  fintech80: fintech80,
  sentenceClassifications: sentenceClassifications,
})
</script>

<style scoped>
.portfolio {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}

#project-github {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-bottom: 3rem;
}

#project-github>.project-github-component-vue {
  margin: 10px 0 10px 0;
  display: block;
}

p {
  max-width: 30rem;
}
</style>